In [33]:
import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans
from sklearn.svm import SVC

In [34]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.ensemble import GradientBoostingClassifier


In [35]:
os.chdir('C:\\Users\\ABC\\3. Edureka\\20. Website deployment\\Dasra')

In [36]:
os.listdir()


['.ipynb_checkpoints',
 'Dasra - All the algos.ipynb',
 'Dasra 2 - All the algos.ipynb',
 'dropout.sav',
 'Graudated or no dataset.csv',
 'train - main.csv']

In [37]:
df = pd.read_csv('train - main.csv')

In [38]:
df['Target'] = df['Target'].map({'Graduate':2,'Enrolled':1, 'Dropout':0})

In [7]:
"""x = df[['Marital status', 'Application mode', 'Previous qualification',
       'Previous qualification (grade)', 'Nacionality', 'Father\'s qualification', 'Admission grade',
       'Displaced', 'Educational special needs','Tuition fees up to date', 'Gender', 'Scholarship holder', 'Age at enrollment', 'Curricular units 1st sem (grade)','Curricular units 2nd sem (grade)', 'Unemployment rate',
       'Inflation rate', 'GDP']]"""

"Previous qualification, Father's qualification, Nacionality, Curricular units 1st sem (grade), 
Curricular units 2nd sem (grade), Tuition fees up to date"

In [39]:
x = df[['Marital status', 'Admission grade',
       'Displaced', 'Educational special needs', 'Gender', 'Scholarship holder', 
        'Age at enrollment', 'Unemployment rate', 'Inflation rate', 'GDP']]

In [40]:
y = df['Target']

In [67]:
#ss = StandardScaler() 
#x = pd.DataFrame(ss.fit_transform(x), columns=x.columns)

In [77]:
"""#Logistic Regresion
lg = LogisticRegression()
model_lr = lg.fit(x_train, y_train)
y_predict_lr = model_lr.predict(x_test)
acc_lr = accuracy_score(y_predict_lr, y_test)
if acc_lr>0.829:
    print(i, acc_lr)"""

'#Logistic Regresion\nlg = LogisticRegression()\nmodel_lr = lg.fit(x_train, y_train)\ny_predict_lr = model_lr.predict(x_test)\nacc_lr = accuracy_score(y_predict_lr, y_test)\nif acc_lr>0.829:\n    print(i, acc_lr)'

In [26]:
[[1,120.1,1,0,0,0,18,7.6,2.6,0.32]]

Marital status  Admission grade  Displaced  Educational special needs  \
0                   1            122.6          0                          0   
1                   1            119.8          1                          0   
2                   1            144.7          0                          0   
3                   1            126.1          1                          0   
4                   1            120.1          1                          0   
...               ...              ...        ...                        ...   
76513               1            116.5          1                          0   
76514               1            131.6          1                          0   
76515               5            123.3          1                          0   
76516               1            124.8          1                          0   
76517               1            131.0          1                          0   

       Gender  Scholarship holder  Age at enrollment  Unemployment rate  \
0           0                   1                 18               11.1   
1           0                   0                 18               11.1   
2           1                   0                 18               16.2   
3           0                   1                 18               11.1   
4           0                   0                 18                7.6   
...       ...                 ...                ...                ...   
76513       0                   1                 18               13.9   
76514       0                   0                 19                9.4   
76515       0                   0                 19                9.4   
76516       0                   0                 18                7.6   
76517       0                   0                 19               15.5   

       Inflation rate   GDP  
0                 0.6  2.02  
1                 0.6  2.02  
2                 0.3 -0.92  
3                 0.6  2.02  
4                 2.6  0.32  
...               ...   ...  
76513            -0.3  0.79  
76514            -0.8 -3.12  
76515            -0.8 -3.12  
76516             2.6  0.32  
76517             2.8 -4.06  

[76518 rows x 10 columns]

In [87]:
y_test

76518    NaN
76519    NaN
76520    NaN
76521    NaN
76522    NaN
          ..
127525   NaN
127526   NaN
127527   NaN
127528   NaN
127529   NaN
Name: Target, Length: 51012, dtype: float64

In [41]:
#Decision Tree
x_train_dt, x_test_dt, y_train_dt,y_test_dt = train_test_split(x,y,test_size=0.2, random_state=42)
dt = DecisionTreeClassifier()
model_dt = dt.fit(x_train_dt, y_train_dt)
y_predict_dt = model_dt.predict(x_test_dt)
acc_dt = accuracy_score(y_test_dt, y_predict_dt)
print(acc_dt)

0.5480266596968113


In [42]:
#RandomForest
x_train_rf, x_test_rf, y_train_rf,y_test_rf = train_test_split(x,y,test_size=0.2, random_state=42)
rf = RandomForestClassifier()
cv_scores = cross_val_score(rf, x, y, cv=5)
model_rf = rf.fit(x_train_rf, y_train_rf)
y_predict_rf = model_rf.predict(x_test_rf)
acc_rf = accuracy_score(y_test_rf, y_predict_rf)
print(acc_rf, cv_scores)

0.5737062205959227 [0.58239676 0.57337951 0.57880293 0.57805659 0.58178135]


In [ ]:
#KNN
import warnings
# Suppress FutureWarnings
warnings.simplefilter(action='ignore', category=FutureWarning)
try: 
    for l in range(278, 285):
        x_train_knn, x_test_knn, y_train_knn, y_test_knn = train_test_split(x,y,test_size=0.2, 
                                                                            random_state=l)
        knn = KNeighborsClassifier()
        model_knn = knn.fit(x_train_knn, y_train_knn)
        y_predict_knn = model_knn.predict(x_test_knn)
        acc_knn = accuracy_score(y_predict_knn, y_test_knn)
        if acc_knn > 0.85:
            print(l, acc_knn)
except ValueError:
    print("Invalid")

In [ ]:
#Support Vector Machines
for m in range(54,56):
    x_train_svc, x_test_svc, y_train_svc, y_test_svc = train_test_split(x,y,test_size = 0.2,
                                                                        random_state = m)
    svc = SVC()
    model_svc = svc.fit(x_train_svc, y_train_svc)
    y_predict_svc = model_svc.predict(x_test_svc)
    acc_svc = accuracy_score(y_test_svc, y_predict_svc)
    if acc_svc > 0.86:
        print(m, acc_svc)

In [ ]:
#GradientBoostingClassifier
for n in range(54, 56):
    x_train_gb, x_test_gb, y_train_gb, y_test_gb = train_test_split(x,y,test_size = 0.2, 
                                                                    random_state = n)
    gb = GradientBoostingClassifier()
    model_gb = gb.fit(x_train_gb, y_train_gb)
    y_predict_gb = gb.predict(x_test_gb)
    acc_gb = accuracy_score(y_predict_gb, y_test_gb)
    if acc_gb > 0.87:
        print(n, acc_gb)

In [27]:
#THIS ONES IT.
#GradientBoostingClassifier_Main
x_train_gb, x_test_gb, y_train_gb, y_test_gb = train_test_split(x,y,test_size = 0.2, 
                                                                random_state = 55)
gb = GradientBoostingClassifier()
model_gb = gb.fit(x_train_gb, y_train_gb)
y_predict_gb = gb.predict(x_test_gb)
acc_gb = accuracy_score(y_predict_gb, y_test_gb)
print(acc_gb)
cv = cross_val_score(gb, x,y,scoring='accuracy', cv=5 )
print(cv)

0.6391139571353894
[0.63846053 0.62774438 0.63434396 0.63249036 0.63817552]


In [28]:
gb.predict_proba([[1,120.1,1,0,0,0,18,7.6,2.6,0.32]])

C:\Users\ABC\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(


array([[0.2752067 , 0.29478638, 0.43000693]])

In [29]:
import pickle
with open('dropout.sav', 'wb') as f1:
    pickle.dump(model_gb, f1)

In [30]:
with open('dropout.sav', 'rb') as f2:
    loaded_bankchurn = pickle.load(f2)

In [31]:
loaded_bankchurn.predict_proba([[1,120.1,1,0,0,0,18,7.6,2.6,0.32]])

C:\Users\ABC\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(


array([[0.2752067 , 0.29478638, 0.43000693]])