In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
import warnings

import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans
from sklearn.svm import SVC

In [2]:
warnings.filterwarnings(action='ignore')

In [3]:
pwd

'C:\\Users\\ABC\\3. Edureka\\20. Website deployment\\Algo 1 - Diabetes'

In [4]:
os.chdir('C:\\Users\\ABC\\6. Datasets')

In [5]:
df = pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [7]:
x = df.iloc[:,0:8]
y = df.iloc[:,8:]

In [11]:
#Logistic Regresion
for i in range(840, 850):
    x_train_lr, x_test_lr, y_train_lr, y_test_lr = train_test_split(x,y,test_size=0.2, random_state=i)
    lg = LogisticRegression()
    model_lr = lg.fit(x_train_lr, y_train_lr)
    y_predict_lr = model_lr.predict(x_test_lr)
    acc_lr = accuracy_score(y_predict_lr, y_test_lr)
    if acc_lr>0.8:
        print(i, acc_lr)

843 0.8051948051948052
847 0.8181818181818182
849 0.8181818181818182


In [13]:
#Decision Tree
for j in range(1242,1250):
    x_train_dt, x_test_dt, y_train_dt, y_test_dt = train_test_split(x,y,test_size=0.2, random_state=j)
    dt = DecisionTreeClassifier()
    model_dt = dt.fit(x_train_dt, y_train_dt)
    y_predict_dt = model_dt.predict(x_test_dt)
    acc_dt = accuracy_score(y_test_dt, y_predict_dt)
    if acc_dt > 0.75:
        print(j, acc_dt)

1248 0.7597402597402597


In [16]:
#KNN
import warnings
# Suppress FutureWarnings
warnings.simplefilter(action='ignore', category=FutureWarning)
try: 
    for l in range(278, 285):
        x_train_knn, x_test_knn, y_train_knn, y_test_knn = train_test_split(x,y,test_size=0.2, 
                                                                            random_state=l)
        knn = KNeighborsClassifier()
        model_knn = knn.fit(x_train_knn, y_train_knn)
        y_predict_knn = model_knn.predict(x_test_knn)
        acc_knn = accuracy_score(y_predict_knn, y_test_knn)
        if acc_knn > 0.70:
            print(l, acc_knn)
except ValueError:
    print("Invalid")

279 0.7597402597402597
280 0.7467532467532467
282 0.7272727272727273
283 0.7012987012987013
284 0.7792207792207793


In [19]:
#Support Vector Machines
for m in range(54,56):
    x_train_svc, x_test_svc, y_train_svc, y_test_svc = train_test_split(x,y,test_size = 0.2,
                                                                        random_state = m)
    svc = SVC()
    model_svc = svc.fit(x_train_svc, y_train_svc)
    y_predict_svc = model_svc.predict(x_test_svc)
    acc_svc = accuracy_score(y_test_svc, y_predict_svc)
    if acc_svc > 0.70:
        print(m, acc_svc)

54 0.7532467532467533
55 0.7272727272727273


In [20]:
#GradientBoostingClassifier
for n in range(54, 56):
    x_train_gb, x_test_gb, y_train_gb, y_test_gb = train_test_split(x,y,test_size = 0.2, 
                                                                    random_state = n)
    gb = GradientBoostingClassifier()
    model_gb = gb.fit(x_train_gb, y_train_gb)
    y_predict_gb = gb.predict(x_test_gb)
    acc_gb = accuracy_score(y_predict_gb, y_test_gb)
    if acc_gb > 0.70:
        print(n, acc_gb)

54 0.7467532467532467
55 0.7337662337662337


In [8]:
#RandomForest
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20, random_state=645)
rf = RandomForestClassifier()
model = rf.fit(x_train, y_train)
y_predict2 = rf.predict(x_test)
acc = accuracy_score(y_test, y_predict2)
print(acc)

0.8441558441558441


In [8]:
cc = confusion_matrix(y_test, y_predict2)
cc

array([[97, 11],
       [13, 33]], dtype=int64)

In [9]:
1-(22/154)

0.8571428571428572

In [10]:
import pickle
filename = 'savedmodel.sav'
pickle.dump(model, open(filename, 'wb'))
load_model = pickle.load(open(filename,'rb'))

In [11]:
pwd

'C:\\Users\\ABC\\6. Datasets'

In [12]:
load_model.predict([[6, 100, 30, 40, 0, 35, 0.66, 45]])

C:\Users\ABC\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [13]:
load_model.predict_proba([[6, 100, 30, 40, 0, 35, 0.66, 45]])

C:\Users\ABC\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([[0.54, 0.46]])

In [14]:
if load_model.predict([[6, 150, 70, 40, 0, 35, 0.66, 45]])[0] == 1:
    print("You have a risk of Diabetes")
else:
    print("You are not at a risk of diabetes")

You have a risk of Diabetes


C:\Users\ABC\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [15]:
load_model.predict_proba([[6, 150, 70, 40, 0, 35, 0.66, 45]])[0][0]

C:\Users\ABC\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


0.26

In [28]:
print(load_model.predict([[6, 150, 70, 40, 0, 35, 0.66, 45]])[0])
load_model.predict_proba([[6, 150, 70, 40, 0, 35, 0.66, 45]])[0][1]

1


0.74

In [29]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [40]:
df['Pregnancies'].describe()

count    768.000000
mean       3.845052
std        3.369578
min        0.000000
25%        1.000000
50%        3.000000
75%        6.000000
max       17.000000
Name: Pregnancies, dtype: float64

In [39]:
for i in df.columns:
    print(i, df[i].min(), df[i].max(),df[i].max(), df[i].mean())

Pregnancies 0 17 17 3.8450520833333335
Glucose 0 199 199 120.89453125
BloodPressure 0 122 122 69.10546875
SkinThickness 0 99 99 20.536458333333332
Insulin 0 846 846 79.79947916666667
BMI 0.0 67.1 67.1 31.992578124999977
DiabetesPedigreeFunction 0.078 2.42 2.42 0.4718763020833327
Age 21 81 81 33.240885416666664
Outcome 0 1 1 0.3489583333333333


In [43]:
for i in df.columns:
    print(i)
    print(df[i].describe())

Pregnancies
count    768.000000
mean       3.845052
std        3.369578
min        0.000000
25%        1.000000
50%        3.000000
75%        6.000000
max       17.000000
Name: Pregnancies, dtype: float64
Glucose
count    768.000000
mean     120.894531
std       31.972618
min        0.000000
25%       99.000000
50%      117.000000
75%      140.250000
max      199.000000
Name: Glucose, dtype: float64
BloodPressure
count    768.000000
mean      69.105469
std       19.355807
min        0.000000
25%       62.000000
50%       72.000000
75%       80.000000
max      122.000000
Name: BloodPressure, dtype: float64
SkinThickness
count    768.000000
mean      20.536458
std       15.952218
min        0.000000
25%        0.000000
50%       23.000000
75%       32.000000
max       99.000000
Name: SkinThickness, dtype: float64
Insulin
count    768.000000
mean      79.799479
std      115.244002
min        0.000000
25%        0.000000
50%       30.500000
75%      127.250000
max      846.000000
Name: In